server:
  port: 8088
  servlet:
    context-path: /demo
logging:
  config: classpath:logback.xml
  level:
    org.springframework.web: DEBUG

spring:
  dubbo:
    application:
     name: cosumer
    registry:
     address: zookeeper://192.168.1.165:2181
    scan: com.example.demo
#db
  datasource:
    name: mydb
    url: jdbc:mysql://192.168.1.145:3308/home_workstation_test
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.domain




